#----------------------------
# GitHub Action Part-1 - Basics
# 
# Copyleft (c) by Dorokhin Andrey 2023.
#---------------------------
name: My-GitHubActions-Basics
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAHE_NAME : "flask-deploy-ver-${{ github.sha }}"
  
on: 
  push:
    branches: 
      - main

jobs:
  my_testing:
    runs-on : ubuntu-latest
    
    steps:
     - name: Print hello message in Testing
       run : echo "Hello World from Testing"
    
     - name: Execute few commands 
       run : |
        echo "Hello Message 1"
        echo "Hello Message 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
          
     - name: List current folder
       run : ls -la
        
     - name: Git clone my repo
       uses: action/checkout@v1
        
     - name: List current folder
       run : ls -la
        
  my_deploy:
    runs-on : ubuntu-latest
    needs: [my_testing]
    env: 
        VAR1 : "This is job Level Variable1"
        VAR2 : "This is job Level Variable2"
      
    steps:
      - name: Print hello message in DSeploy
        run: |
          echo "Var1 - ${{ env.VAR1 }}"
          echo "Var2 - ${{ env.VAR2 }}"
          echo "Var3 - $LOCAL_VAR"
        env:
          LOCAL_VAR: "This is supper local Environment variable"
       
      - name: Print hello message in Deploy
        run: echo "Hello World from Deploy job"

      - name: Printing Deployment package
        run : echo "Deploy package name is ${{ env.DEPLOY_PACKAHE_NAME }}"

      - name: Lets test some package if they are here 1
        run : aws --version
         
      - name: Lets test some package if they are here 2
        run : zip --version
      
      
      
